version: '3'
services:
  app:
    container_name: vue-app
    build:
      context: ./dockerfiles/app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true